- name: Inject SSH Key to remote hosts
  ssh_copy_id:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ssh_public_key: "{{ ssh_public_key }}"
    ssh_port: "{{ ssh_port }}"

